---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.2
_src_path: gh:radio-aktywne/template-app-litestar
accountname: radio-aktywne
appname: emirecorder
description: Emission recording 🎥
docs: true
docsurl: https://radio-aktywne.github.io/app-emirecorder
email: it@radioaktywne.pl
envprefix: EMIRECORDER
importname: emirecorder
registry: true
releases: true
reponame: app-emirecorder
repourl: https://github.com/radio-aktywne/app-emirecorder
