services:
  emirecorder:
    build:
      context: ./
      network: host
    network_mode: host
    environment:
      - "EMIRECORDER__SERVER__HOST=${EMIRECORDER__SERVER__HOST:-0.0.0.0}"
      - "EMIRECORDER__SERVER__PORT=${EMIRECORDER__SERVER__PORT:-31000}"
      - "EMIRECORDER__RECORDER__HOST=${EMIRECORDER__RECORDER__HOST:-0.0.0.0}"
      - "EMIRECORDER__RECORDER__PORTS=${EMIRECORDER__RECORDER__PORTS:-31000}"
      - "EMIRECORDER__RECORDER__TIMEOUT=${EMIRECORDER__RECORDER__TIMEOUT:-PT1M}"
      - "EMIRECORDER__RECORDER__WINDOW=${EMIRECORDER__RECORDER__WINDOW:-PT1H}"
      - "EMIRECORDER__EMIARCHIVE__HOST=${EMIRECORDER__EMIARCHIVE__HOST:-localhost}"
      - "EMIRECORDER__EMIARCHIVE__PORT=${EMIRECORDER__EMIARCHIVE__PORT:-30000}"
      - "EMIRECORDER__EMIARCHIVE__USER=${EMIRECORDER__EMIARCHIVE__USER:-readwrite}"
      - "EMIRECORDER__EMIARCHIVE__PASSWORD=${EMIRECORDER__EMIARCHIVE__PASSWORD:-password}"
      - "EMIRECORDER__EMIARCHIVE__BUCKET=${EMIRECORDER__EMIARCHIVE__BUCKET:-live}"
      - "EMIRECORDER__EMISHOWS__HOST=${EMIRECORDER__EMISHOWS__HOST:-localhost}"
      - "EMIRECORDER__EMISHOWS__PORT=${EMIRECORDER__EMISHOWS__PORT:-35000}"
