---
services:
  emirecorder:
    build: .
    network_mode: host
    environment:
      - "EMIRECORDER__SERVER__HOST=${EMIRECORDER__SERVER__HOST:-0.0.0.0}"
      - "EMIRECORDER__SERVER__PORT=${EMIRECORDER__SERVER__PORT:-31000}"
      - "EMIRECORDER__RECORDING__TIMEOUT=${EMIRECORDER__RECORDING__TIMEOUT:-60}"
      - "EMIRECORDER__RECORDING__FORMAT=${EMIRECORDER__RECORDING__FORMAT:-ogg}"
      - "EMIRECORDER__EMIARCHIVE__HOST=${EMIRECORDER__EMIARCHIVE__HOST:-localhost}"
      - "EMIRECORDER__EMIARCHIVE__PORT=${EMIRECORDER__EMIARCHIVE__PORT:-30000}"
      - "EMIRECORDER__EMIARCHIVE__USER=${EMIRECORDER__EMIARCHIVE__USER:-readwrite}"
      - "EMIRECORDER__EMIARCHIVE__PASSWORD=${EMIRECORDER__EMIARCHIVE__PASSWORD:-password}"
      - "EMIRECORDER__EMIARCHIVE__BUCKET=${EMIRECORDER__EMIARCHIVE__BUCKET:-live}"
