services:
  emirecorder:
    build:
      context: ./
      network: host
    environment:
      - "EMIRECORDER__SERVER__HOST=${EMIRECORDER__SERVER__HOST:-0.0.0.0}"
      - "EMIRECORDER__SERVER__PORT=${EMIRECORDER__SERVER__PORT:-31000}"
      - "EMIRECORDER__RECORDER__HOST=${EMIRECORDER__RECORDER__HOST:-0.0.0.0}"
      - "EMIRECORDER__RECORDER__PORTS=${EMIRECORDER__RECORDER__PORTS:-31000}"
      - "EMIRECORDER__RECORDER__TIMEOUT=${EMIRECORDER__RECORDER__TIMEOUT:-PT1M}"
      - "EMIRECORDER__RECORDER__WINDOW=${EMIRECORDER__RECORDER__WINDOW:-PT1H}"
      - "EMIRECORDER__EMIARCHIVE__S3__SECURE=${EMIRECORDER__EMIARCHIVE__S3__SECURE:-false}"
      - "EMIRECORDER__EMIARCHIVE__S3__HOST=${EMIRECORDER__EMIARCHIVE__S3__HOST:-localhost}"
      - "EMIRECORDER__EMIARCHIVE__S3__PORT=${EMIRECORDER__EMIARCHIVE__S3__PORT:-30000}"
      - "EMIRECORDER__EMIARCHIVE__S3__USER=${EMIRECORDER__EMIARCHIVE__S3__USER:-readwrite}"
      - "EMIRECORDER__EMIARCHIVE__S3__PASSWORD=${EMIRECORDER__EMIARCHIVE__S3__PASSWORD:-password}"
      - "EMIRECORDER__EMIARCHIVE__S3__BUCKET=${EMIRECORDER__EMIARCHIVE__S3__BUCKET:-live}"
      - "EMIRECORDER__EMISHOWS__HTTP__SCHEME=${EMIRECORDER__EMISHOWS__HTTP__SCHEME:-http}"
      - "EMIRECORDER__EMISHOWS__HTTP__HOST=${EMIRECORDER__EMISHOWS__HTTP__HOST:-localhost}"
      - "EMIRECORDER__EMISHOWS__HTTP__PORT=${EMIRECORDER__EMISHOWS__HTTP__PORT:-35000}"
      - "EMIRECORDER__EMISHOWS__HTTP__PATH=${EMIRECORDER__EMISHOWS__HTTP__PATH:-}"
    network_mode: host
