---
services:
  emirecorder:
    build: .
    network_mode: host
    environment:
      - "EMIRECORDER_SERVER__HOST=${EMIRECORDER_SERVER__HOST:-0.0.0.0}"
      - "EMIRECORDER_SERVER__PORT=${EMIRECORDER_SERVER__PORT:-31000}"
      - "EMIRECORDER_SERVER__CONCURRENCY=${EMIRECORDER_SERVER__CONCURRENCY:-}"
      - "EMIRECORDER_SERVER__BACKLOG=${EMIRECORDER_SERVER__BACKLOG:-2048}"
      - "EMIRECORDER_SERVER__KEEPALIVE=${EMIRECORDER_SERVER__KEEPALIVE:-5}"
      - "EMIRECORDER_RECORDING__TIMEOUT=${EMIRECORDER_RECORDING__TIMEOUT:-60}"
      - "EMIRECORDER_RECORDING__FORMAT=${EMIRECORDER_RECORDING__FORMAT:-ogg}"
      - "EMIRECORDER_EMIARCHIVE__HOST=${EMIRECORDER_EMIARCHIVE__HOST:-localhost}"
      - "EMIRECORDER_EMIARCHIVE__PORT=${EMIRECORDER_EMIARCHIVE__PORT:-30000}"
      - "EMIRECORDER_EMIARCHIVE__USER=${EMIRECORDER_EMIARCHIVE__USER:-readwrite}"
      - "EMIRECORDER_EMIARCHIVE__PASSWORD=${EMIRECORDER_EMIARCHIVE__PASSWORD:-password}"
      - "EMIRECORDER_EMIARCHIVE__BUCKET=${EMIRECORDER_EMIARCHIVE__BUCKET:-live}"
